version: '3.8'

services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app/
    # networks:
    #   - mynetwork
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6004:5432
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      
    # networks:
    #   - mynetwork

volumes:
  postgres_data:
    driver: local

# networks:
#   mynetwork:
#     driver: bridge

